Sargassoweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('News&Updates/',include('blog.urls')),
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('Products/',include('shop.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views



app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail,name='post_detail'),
    #path('post/<slug>/', views.post, name = 'post'),
   # path('about/', views.about,name = 'about' ),
    #path('postlist/<slug>/', views.postlist, name = 'postlist'),
   # path('posts/', views.allposts, name = 'allposts'),
]

home/urls.py
from django.urls import path,include
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


app_name = "home" 

urlpatterns = [
    path('',views.index,name="index"),
    path('About-Us',views.about,name="profile"),
    path('Product-Impact',views.Product_impact,name="impact"),
    path('Plastics-Recycling',views.Recycle,name="recycle"),
    path('3D-Printing',views.Print,name="print"),
    path('Our-Team',views.Team,name="team"),
    path('Careers&Opportunities',views.Job,name="jobs"),
    path('SupportUs/Donate',views.Donate,name="donate"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views



app_name = "shop"

urlpatterns = [
    path('', views.Products, name='products'),

]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import  reverse

User = get_user_model()
CATEGORY = [
    ('NEWS', 'News'),
    ('EVENT', 'Event'),
]
# Create your models here.
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username

class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    category=models.CharField(max_length=50,choices=CATEGORY)
    featured = models.BooleanField(default=False)

    class Meta:
        ordering=('-timestamp',)
    def __str__(self):
        return self.title
   

home/models.py
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    facebook = models.TextField()
    linkedin = models.TextField()
    twitter = models.TextField()
    linkedin = models.TextField()
    img = models.ImageField(blank=True)

    def __str__(self):
         return self.name

class Profile(models.Model):
    id = models.BigAutoField(primary_key=True)
    mission = models.TextField()
    vision = models.TextField()
    history = models.TextField()
    

class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    testimony = models.TextField()
    img = models.ImageField(blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title

class Contact(models.Model):
    title = models.CharField(max_length=100)
    service_type = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

class Job(models.Model):
    title = models.CharField(max_length=100)
    location = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    education = models.TextField()
    location = models.TextField()
    experience = models.TextField()
    requirements = models.TextField()

    def __str__(self):
        return self.title

shop/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email','service_type', 'message']

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Post



def post_list(request):
    latest1 = Post.objects.filter(category='NEWS').order_by('-timestamp')[:1]
    latest = Post.objects.filter(category='NEWS').order_by('-timestamp')[1:]
    events = Post.objects.all().filter(category='EVENT').order_by('-timestamp')[0:3]
    posts = Post.objects.all().filter(category='NEWS')[1:]
    page_num = request.GET.get('page', 1)
    paginator = Paginator(posts, 8)
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)

    
    context= {
     
        'posts': posts,
        'latest':latest,
        'latest1':latest1,
        'page_obj': page_obj,
        'events': events,
        

       
    }
    return render(request,'home/index.html',context)


def post_detail(request,slug):

    post = get_object_or_404(Post, slug=slug)
    latest = Post.objects.filter(category='NEWS').order_by('-timestamp')[0:3]
    events = Post.objects.all().filter(category='EVENT').order_by('-timestamp')[0:3]
    context = {
        'post': post,
        'latest':latest,
        'events': events,
    }
    return render(request,'single.html',context )

home/views.py
from django.shortcuts import render
from blog.models import  Post
from .models import  Testimonial, Employee, Profile, Project, Job
from django.shortcuts import get_object_or_404
from django.db.models import Sum
from django.http import JsonResponse

# Create your views here.

def index(request):
    events = Post.objects.all().filter(category='EVENT').order_by('-timestamp')[0:3]
    testimonial = Testimonial.objects.all()
    project = Project.objects.all()
    latest = Post.objects.order_by('-timestamp')[0:3]
    context= {
        'project':project,
        'latest': latest,
        'testimonial':testimonial,
        
    }
    return render(request, 'index.html', context)

def about(request):
    employee = Employee.objects.all()
    profile=get_object_or_404(Profile) 
    latest = Post.objects.order_by('-timestamp')[0:3]
    context= {
      'employee':employee,
       'profile':profile,
       'latest': latest,
    }
    return render(request,'profile.html', context)

def Team(request):
    employee = Employee.objects.all()
    context= {
      'employee':employee,

    }

    return render(request,'team.html',context)


def Product_impact(request):

    return render(request, 'impact.html')

def Recycle(request):


    return render(request, 'recycle.html')

def Print(request):

    return render(request, 'print.html')
    
def Job(request):

    return render(request, 'jobs.html')
def Donate(request):

    return render(request, 'donate.html')

shop/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from blog.models import Post

def Products(request):
    latest1 = Post.objects.filter(category='NEWS').order_by('-timestamp')[:1]
    latest = Post.objects.filter(category='NEWS').order_by('-timestamp')[0:3]
    events = Post.objects.all().filter(category='EVENT').order_by('-timestamp')[0:3]
    posts = Post.objects.all().filter(category='NEWS')[1:]
    page_num = request.GET.get('page', 1)
    paginator = Paginator(posts, 8)
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)

    
    context= {
     
        'posts': posts,
        'latest':latest,
        'latest1':latest1,
        'page_obj': page_obj,
        'events': events,
        

       
    }
    return render(request,'shop.html',context)

blog/templates/blog.html
{% extends 'base_blog.html' %} 
{% block content%}
  <!-- Page Header Start -->
  <div class="container-fluid page-header py-0 mb-0 wow fadeIn" data-wow-delay="0.1s">
	<div class="container text-center py-4">
		<h1  class="mb-4  fs-1 fw-bold text-white text-left"><span class="mb-4 fw-semi-bold">Sargasso Blog & News </span> </h1>
	
	</div>
</div>
<!-- Page Header End -->
<!-- ======= Hero Slider Section ======= -->

    <section id="hero-slider" class="hero-slider">
      <div class="container-md pt-0 mt-0" data-aos="fade-in">
        <div class="row">
          
          <div class="col-12">
            <div class="container text-center py-0">
              <h4  class="mb-0 fs-4 fw-light  text-start"><span class="mb-0 fw-semi-bold">Upcoming Events </span> </h4>
            </div>
            <div class="swiper sliderFeaturedPosts">
              <div class="swiper-wrapper">
              
                <div class="swiper-slide">
                  
                {% if events%}
                {% for events in events  %}
                  <a href="{% url 'blog:post_detail' events.slug %}" class="img-bg d-flex align-items-end" style="background-image: url('{{ events.thumbnail.url }}');">
                    <div class="img-bg-inner">
                      <h2 class='text-warning fw-semi-bold'>{{ events.title }}</h2>
                      <p class='text-warning fw-semi-bold'>{{ events.content }}</p>
                    </div>
                  </a>
                </div>

                {% endfor%}
                         {% else %}
                        <p>No Events Available</p>
                        {% endif%}

                
              </div>
              <div class="custom-swiper-button-next">
                <span class="bi-chevron-right"></span>
              </div>
              <div class="custom-swiper-button-prev">
                <span class="bi-chevron-left"></span>
              </div>

              <div class="swiper-pagination"></div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Hero Slider Section -->

    <!-- ======= Post Grid Section ======= -->
    <section id="posts" class="posts">
      <div class="container" data-aos="fade-up">
        <div class="row g-5">
          <div class="container text-center py-0">
            <h4  class="mb-0 fs-4  text-center "><span class="mb-0 fw-semi-bold">News And Updates </span> </h4>
          </div>
            {% if latest1%}
            {% for latest1 in latest1  %}
          <div class="col-lg-4">
            <div class="post-entry-1 lg">
              <a href="{% url 'blog:post_detail' latest1.slug %}"><img src="{{ latest1.thumbnail.url }}" alt="" class="img-fluid" height="120px" width="450px"></a>
              <div class="post-meta"><span class="date">{{ latest1.category }}</span> <span class="mx-1">&bullet;</span> <span>{{ latest1.timestamp | date:"d M Y"}}</span></div>
              <h4 class="fw-semi-bold text-black mb-1"><a href="{% url 'blog:post_detail' latest1.slug %}">{{ latest1.title|upper }}</a></h4>
              <p class="mb-4 d-block">. {{ latest1.content | truncatechars:110 }}</p>

              <div class="d-flex align-items-center author">
                <div class="photo"><img src="assets/img/person-1.jpg" alt="" class="img-fluid"></div>
                <div class="name">
                  <h3 class="m-0 p-0">{{ latest1.author }}</h3>
                </div>
              </div>
            </div>
            {% endfor%}
                         {% else %}
                        <p>No News  Available</p>
                        {% endif%}
          </div>

          <div class="col-lg-8">
            <div class="row g-1">
                {% if posts%}
            {% for posts in page_obj  %}
                <div class="col-lg-4 g-1">
                  <a href="{% url 'blog:post_detail' posts.slug %}"><img src="{{ posts.thumbnail.url }}" alt="" class="img-rounded" height="170px" width="270px"></a>
                  <div class="post-meta mt-2"><span class="date">{{ posts.category }}</span> <span class="mx-1">&bullet;</span> <span>{{ posts.timestamp | date:"d M Y"}}</span></div>
                  <h6 class="fw-fw-semi-bold text-dark"><a href="{% url 'blog:post_detail' posts.slug %}">{{ posts.title|upper  }}</a></h6>
                </div>
                {% endfor%}
                         {% else %}
                        <p>No News  Available</p>
                        {% endif%}

              
          </div>
       
         
        </div>
       <!-- End .row -->
       <ul class="pagination mx-auto justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
        {% for i in page_obj.paginator.page_range %}
              {% if page_obj.number == i %}
              <li class="page-item"><a class="page-link" href="#">{{ i }}</a></li>
              {% else %}
              
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
         {% if page_obj.has_next %}
         <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="#">Next</a></li>
          {% endif %}
          
      </ul>
    </section> <!-- End Post Grid Section -->


    {% endblock%}

blog/templates/news.html
{% extends 'base_blog.html' %} 
{% block content%}
  <!-- Page Header Start -->
  <div class="container-fluid page-header py-2 mb-0 wow fadeIn" data-wow-delay="0.1s">
	<div class="container text-center py-4">
		<h1  class="mb-4  fs-1 fw-bold text-white text-left"><span class="mb-4 fw-semi-bold">Sargasso Blog & News </span> </h1>
	
	</div>
</div>
<!-- Page Header End -->
        <div class="container-fluid">
            
            <div class="row align-items-start">
                <div class="col-sm-11 offset-1 ">
                    <div class="row">
                        <h4 class="fw-semi-bold fs-1 mt-4 mb-4 text-black text-center">Recent from blog</h4>
                        {% if posts%}
                        {% for posts in page_obj  %}
                        <div class="col-sm-4" >
                            <div class="blog-grid">
                                <div class="blog-img">
                                    <div class="date">
                                        <span>{{ posts.timestamp | date:"d"}}</span>
                                        <label class="text-center">{{ posts.timestamp | date:"M" }}</label>
                                    </div>
                                    <a href="#">
                                        <img src="{{ posts.thumbnail.url }}" title="ocean_plastics" alt="" height="120px" width="350px">
                                    </a>
                                </div>
                                <div class="blog-info">
                                    <h5 class="text-capitalize"><a href="{% url 'blog:post_detail' posts.slug %}" class="text-capitalize">{{ posts.title }}</a></h5>
                              <p>{{ posts.content | truncatechars:110 }}</p>
                                    <div class="d-flex text-small mt-4">
                                        <span class="text-muted fw-semi-bold fs-6">{{ posts.timestamp | date:"d,M Y" }}</span>
                                        <span class="text-muted fw-semi-bold fs-6 mx-2">.3 Min Read</span>
                                    </div>
                                </div>
                            </div>
                        
                        </div>
                        {% endfor%}
                         {% else %}
                        <p>No News  Available</p>
                        {% endif%}
                    </div>
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                      </ul>
                </div>
          
               

               

              
         
            </div>
        </div>

    {% endblock%}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
            <title>{% block title %}{% endblock %}</title>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
            <!-- Ensures optimal rendering on mobile devices. -->
            <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
            <!-- Optimal Internet Explorer compatibility -->
            <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
            <meta name="description" content="Sargasso Reclamation is a Kenya based Company dedicated to sustainable solutions to cleanup the oceans of plastic.Our aim to remove atleast 80% of plastic from our ocean and transform to useful products.">
            <meta property="og:locale" content="en_US">
            <meta property="og:type" content="website">
            <meta property="og:title" content="Sargasso Reclamation">
            <meta property="og:description" content="Sargasso Reclamation is a Kenya based Company dedicated to sustainable solutions to cleanup the oceans of plastic.Our aim to remove atleast 80% of plastic from our ocean and transform to useful products.">
            <meta property="og:url" content="https://www.sargasso-reclamation.com/">
            <meta property="og:site_name" content="Sargasso Reclamation">
            <meta property="article:publisher" content="https://web.facebook.com/Sargasso.Reclamation">
            <!-- Favicon -->
            <link rel="canonical" href="https://www.sargasso-reclamation.com/">
            <link rel="icon" href="{% static 'img/favicon.webp'%}" type="image/x-icon" alt="sargasso-reclamation">
            <link rel="shortcut icon" href="{% static 'img/favicon.webp'%}" type="image/x-icon" alt="sargasso-reclamation"/>
            <link rel="preconnect" as="font" href="https://fonts.googleapis.com" crossorigin>
            <link rel="preconnect" as="font" href="https://fonts.gstatic.com" crossorigin>
            <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" type="text/css">
            <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
             <style>
            @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;800;900&display=swap');
            </style>
            <script src="https://kit.fontawesome.com/046ef5155f.js" crossorigin="anonymous" defer ></script>
            <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js' defer ></script>
            <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js' defer ></script>
            <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P8QNQP1TXF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P8QNQP1TXF');
</script>

  </head>
    
<body>
    <div class="container-fluid footer-a">
        <div class="row gx-0 d-none d-lg-flex">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center me-2">
                    <span class="fa fa-phone-alt me-2 text-warning"></span>
                    <span>+254112011918</span>
                </div>
                <div class="h-100 d-inline-flex align-items-center">
                    <span class="fa fa-envelope me-2 text-info"></span>
                    <span>info@sargasso.io</span>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center mx-n2">
                    <span>
                         <a class="btn btn-link text-primary" href="https://twitter.com/SargassoNets" aria-label="sargasso reclamation twitter page"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-link text-info" href="https://www.facebook.com/Sargasso.Reclamation" aria-label="sargasso reclamation facebook page"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-link text-primary" href="https://www.linkedin.com/company/sargasso-reclamation/" aria-label="sargasso reclamation youtube channel"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-link text-info" href="https://www.linkedin.com/company/sargasso-reclamation" aria-label="sargasso reclamation linkedin page"><i class="fab fa-linkedin-in"></i></a>

                </span>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

   <!-- Navbar Start -->
   <nav class="navbar navbar-expand-lg navbar sticky-top p-0 bg-white">
<a href="{% url 'home:index'%}" class="navbar-brand d-flex align-items-center mx-4" aria-label="sargasso homepage">
        <img class="img-fluid" src="{% static 'img/Sargasso.webp'%}" alt="Sargasso Reclamtion" height="60" width="240">
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-label="collapse menu">
        <span class="navbar-toggler-icon text-info"><i class="fa fa-bars" aria-hidden="true"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0 " id="the_menu">
            <a href="{% url 'home:index'%}"  class="nav-item nav-link fw-bold beBZxq" aria-label="home">Home</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-item nav-link fw-bold beBZxq" data-bs-toggle="dropdown" aria-label="about-us link">About Us</a>
                <div class="dropdown-menu">
                    <a href="{% url 'home:profile'%}" class="dropdown-item " >Our Story</a>
                    <a href="{% url 'home:impact'%}" class="dropdown-item">Our Impact</a>
                    <a href="{% url 'home:impact'%}" class="dropdown-item">Careers</a>
                    
                </div>
            </div>
             <div class="nav-item dropdown">
                <a href="#" class="nav-item nav-link fw-bold beBZxq" data-bs-toggle="dropdown" aria-label="who are we link">Who We Are</a>
                <div class="dropdown-menu ">
                    <a href="{% url 'home:team'%}" class="dropdown-item">Meet Our Team</a>
                    <a href="#" class="dropdown-item" >Our Partners</a>
                    
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-item nav-link fw-bold beBZxq" data-bs-toggle="dropdown" aria-label="what we do link">What We Do</a>
                <div class="dropdown-menu ">
                    <a href="{% url 'home:recycle'%}" class="dropdown-item">We Recycle </a>
                    <a href="{% url 'home:print'%}" class="dropdown-item">3D Printing</a>
                    
                </div>
            </div>
            <a href="{% url 'shop:products'%}" class="nav-item nav-link fw-bold beBZxq" aria-label="Product">Our Products</a>
            <a href="{% url 'home:donate'%}" class="nav-item nav-link fw-bold beBZxq " aria-label="Support">Support Us</a>
     
        </div>

    </div>
</nav>
<!-- Navbar End -->

    {% block content %}

    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid footer footer-a" >
  
            
        <div class="container py-4">
            <div class="row ">
                <div class="col-lg-5 col-md-5">
                    <h4 class="footer-heading  text-left beBZxq mb-2 text-white">SARGASSO RECLAMATION</h4>
                    <p class="fw-300" ><i class="fa fa-map-marker-alt me-3"></i>Plastiki House,Casuarina,<br> P.O BOX 5319-80200<br> Malindi,Kenya</p>
                    <p class="fw-300 " ><i class="fa fa-phone-alt me-3 "></i>+254112011918</p>
                    <p class="fw-300 " ><i class="fa fa-envelope me-3"></i>info@sargasso.io</p>
                    <div class="d-flex pt-1">
                        <a class="btn btn-square text-primary btn-outline-white rounded-circle me-2" href="https://twitter.com/SargassoNets" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square text-success btn-outline-white rounded-circle me-2" href="https://www.facebook.com/Sargasso.Reclamation" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square text-danger btn-outline-white rounded-circle me-2" href="https://www.linkedin.com/company/sargasso-reclamation/" aria-label="Youtube"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square text-info btn-outline-white rounded-circle me-2" href="https://www.linkedin.com/company/sargasso-reclamation" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    
                </div>
                <div class="col d-none d-sm-block ">
                    <h5 class="fw-300  text-left beBZxq mb-4 text-white">ABOUT US</h5>
                    <ul class="list-unstyled mt-6 pt-6">
                    
                      <li><a href="#" class="text-white" ><i class="fa fa-chevron-right me-3" ></i> Careers</a></li>
                      <li><a href="{% url 'home:recycle'%}"  class="text-white"><i class="fa fa-chevron-right me-3"></i>  Recyling</a></li>
                      <li><a href="#" class="text-white" ><i class="fa fa-chevron-right me-3" ></i> Media gallery</a></li>
                      <li><a href="#" class="text-white"><i class="fa fa-chevron-right me-3 fa-1x" ></i> Partners</a></li>
                      <li></li>
                    </ul>
                  </div>
                <div class="col d-none d-sm-block ">
                    <h5 class="fw-300  text-left beBZxq mb-4 text-white">HELP</h5>
                    <ul class="list-unstyled mt-6 pt-6">
                    <li><a href="#" class="text-white" ><i class="fa fa-chevron-right"></i> Support Us</a></li>
                    <li><a href="{% url 'shop:products'%}" class="text-white"  ><i class="fa fa-chevron-right"></i> Merchandise</a></li>
                    <li><a href="#" class="text-white"  ><i class="fa fa-chevron-right" ></i> FAQ</a></li>
                    </ul>
                  </div>

                
            <div class="col d-none d-sm-block ">
                    <h5 class="fw-300  text-left beBZxq mb-4 text-white">LEGAL</h5>

            <ul class="mt-6 pt-6 list-unstyled">
                <li><a href="#" class="text-white" ><i class="fa fa-chevron-right"></i> Privacy and Cookies</a></li>
            </ul>
                </div>
            </div>
        </div>
   
<!-- Footer End -->

<span class="footer-line"></span>
<!-- Copyright Start -->
    
            <div class="row">
                <div class="col-md-12 text-center text-md-center p-3 mb-md-0">
                   <span class="text-white fs-6">Sargasso Reclamation  &copy; 2022 All Right Reserved.<br>Powered by <a class="text-warning" href="#">Sargasso IT Team</a></span>
                </div>
            </div>
    </div>
<!-- Copyright End -->

<!--Start of Tawk.to Script-->
<script type="text/javascript" defer >
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/64a67de1cc26a871b026ae94/1h4l5nehl';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
<!-- MDB -->
<script type="text/javascript" src="{% static 'md.js' %}" defer 
></script>
<script src="{% static 'bootstrap.bundle.min.js' %}" defer ></script>
 
</body>

</html>